# Generated by Django 3.2.5 on 2021-07-25 15:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('OWNER', models.CharField(max_length=30)),
                ('NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('USERID', models.CharField(max_length=30)),
                ('MOVIEID', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=30)),
                ('STARTDATE', models.DateField()),
                ('ENDDATE', models.DateField()),
                ('CINEMANAME', models.CharField(max_length=30)),
                ('CATEGORY', djongo.models.fields.JSONField()),
            ],
        ),
    ]
