# Generated by Django 3.2.5 on 2021-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='NAME',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='OWNER',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='MOVIEID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='USERID',
            field=models.CharField(max_length=40),
        ),
    ]
